### ISSUE TITLE
Guidelines for supporting multiple "envoy" databases with a single Envoy service

### ISSUE THREAD

**Issue by leyk0001** [cloudant-labs/envoy#172]
Hello. I am looking for guidelines on the approach (assuming one is feasible) for the use case where I need to have multiple databases for a single mobile user.

Basically, I have a mobile app that records events into daily logs. The mobile app user needs to see and be able to edit events for last 7 days only. If mobile app user switches to another mobile device the events for last 7 days should replicate to that device. There is also a web portal - this is just a normal web application. The portal user should be able to query events for all mobile app users for the last year, not just the last 7 days. So basically I can't delete all events, but I can't show them to mobile app user either.

One simple and efficient solution for me would be to create a separate database for each day of the year. This way, I can simply delete "old" databases from mobile device but allow them to be queried from web portal. This would mean, however, that instead of a single "envoy" database on Cloudant, I would need to have something like "envoy-1-1-2017", "envoy-1-2-2017", etc. 

I would really appreciate if someone could give me and advice or direction to follow on how I can use Envoy to make this work.

Thanks!
-- Michael

**Comment by glynnbird** [comment]
In *theory*, Envoy could allow many databases to be targeted. It is just an Express app that listens for a number of incoming API calls e.g.

https://github.com/cloudant-labs/envoy/blob/master/lib/routes/all-docs.js#L26

^ this line handles requests for 'GET /db/_all_docs'. By replacing such lines with 

```
router.get('/:dbname/_all_docs', auth.isAuthenticated, function(req, res) {
```

if could be rewritten to handle multiple databases.

But that doesn't get you what you want. If I understand you requirements correctly, you want:

1) a means of getting the last 7 days data from the server-side to the client side (when the user switches devices)
2) a means of uploading new logs from the client to server side

(1) could be achieved by creating an API call that queries the database for data owned by that user that was made in the last 7 days - not "replication" as such, just a query
(2) use "push" replication to only ever write data from client to server (apart from in the case of (1))

The "push replication" scenario (client to server) is very easy to implement. It means you can leave Envoy with one ever-growing database for all users data. Instead of using "pull replication" to recreate data on the client side, just create a view which extracts the data you need and writes it to your local device.

Unfortunately, there isn't a "replicate data based on an ad-hoc query" functionality at the moment.

**Comment by numerized** [comment]
Opening this conversation in my team exactly today.
Why not using filtered replication on envoy pull and exclude document types logs older than a date ?

**Comment by leyk0001** [comment]
@glynnbird Hi Glynn, thanks for quick response! I am still new to CouchDB and Envoy,  please keep that in mind if I write something that makes little sense or if I seem to miss an obvious solution :)

If I understand your “query” approach correctly, I would do a “query” which would return all documents for the user for the last 7 days and then save the result of that query to my local “couch-like” datastore (e.g. PourchDB or Cloudant Sync). I could then read from and write to that local datastore and at some point (e.g. periodically) do “push” synchronization to backend. Is this correct?

@numerized Hi. I haven’t played with filtered replication yet but from what I’ve read, it seems like it should work. Are there any server-side performance penalties to it?

**Comment by glynnbird** [comment]
@numerized you could do that. But Envoy is designed to store lots of users' data in a single database. If, as a remote user, you wanted to run filtered replication to extract data for a date range, then the changes feed would run through every user's data set to get to the slice of one user you are interested in. So it could work for you, but performance would depend on data size and number of users

**Comment by glynnbird** [comment]
@leyk0001 Envoy helps you out a lot in the case of lots of remote users collecting logs. You get
- a server-side data set which is the total of all users' data
- each user's slice of the data is walled off from each other e.g. you can replicate to and from a single users slice of the data
- in the use-case of client-side logs being pushed to the server, Envoy would provide a scalable and performant solution allowing the whole data set to be aggregated for reporting.

The extra functionality you are proposing (making daily databases) somewhat takes away from the advantages above. Now you no longer have a single place that can be queried to get a report - you have to interrogate many individual pots of data to get the whole picture. This is not supported by Envoy today.

In terms of performance, pushing data to the server is more performant than pulling data from the server: in short "pushing" is fed from your local database's changes feed, whereas "pulling" is fed from the remote side's changes feed (which includes all other users' changes). So your use-case is not unreasonable, just that the "pulling" part of the operation (which you say only occurs when a user switches phones) is a pinch point that you might want to avoid (depending on data size and number of users)

**Comment by ban72-dev** [comment]
Hi Glynnbird,
Can you advise how to re write the mentioned line to handle more that one database? 
Currently I'm using two separate envoy apps to access one database each, while sharing the same user database. I have having a lot of errors when attempting to push/pull although authentication works fine, I get an unauthorised error upon a push or pull. especially when using iphone/ipad.
Thanks,
Niall
