### ISSUE TITLE
Simulate _changes from _all_docs

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#46]
Using a filtered version of _changes will be hopelessly inefficient.

**Comment by xpqz** [comment]
Simulating _changes via _all_docs is a temporary measure: eventually the _changes end point should go away - but as a first step it allows our tests to run, although won't support deletions.

**Comment by glynnbird** [comment]
I had a quick go at simulating a changes feed from all_docs, but the sequence numbers are the issue. It's easy enough to create a `since=0` changes feed simulated from _all_docs (deletions notwithstanding), but the problem comes when the replicator asks for changes with a value of `since` that is non zero. We don't know what to reply with then. If we reply with everything then the replicator asks again and it ends up in an infinite loop. If we reply with nothing, then no changes are ever replicated to the target.

Parking this for the moment.

**Comment by glynnbird** [comment]
For reference, I got this far:

```
$ ccurl '/mbaas/_changes' 
{"results":[
{"id":"a","seq":"1-1","changes":[{"rev":"1-e3f3924405fe037797a05f048ed9aca8"}]},
{"id":"b","seq":"2-2","changes":[{"rev":"1-4fdab56ed1ec4d86259402393a66a6b2"}]},
{"id":"c","seq":"3-3","changes":[{"rev":"1-55216e92bfb7cfd7499cb64f3b8aedc5"}]}
],"last_seq":"3-3","pending":0}
```

**Comment by xpqz** [comment]
This seems like a non-starter.
