### ISSUE TITLE
Cloudant Query support

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#7]
In order to support CQ we need two new end points: `/DB/_index` and `/DB/_find`.

A POST to _index will need to support a few variants:

```json
{
    "index": {
        "fields": ["foo"]
    },
    "name" : "foo-index",
    "type" : "json"
}
```
and
```json
{
"fields": [
      {"name": "married", "type": "boolean"},
      {"name": "lastname", "type": "string"},
      {"name": "year-of-birth", "type": "number"}
    ],
    "name" : "foo-index",
    "type" : "json"
}
```
We need to inject the com.cloudant.meta.auth.users field (how I wish we'd called it something else...) either as a string, or as an object appropriately.

On the `_find` endpoint we need to encapsulate whatever selector the user issued into an `"$and"`. Given

```json
 "selector": {
    "$and": [
      {
        "_id": { "$gt": null }
      },
      {
        "year": {
          "$in": [2014, 2015]
        }
      }
    ]
  }
```
we'd want that transformed to something like 
```json
 "selector": {
  "$and": [
     "$and": [
       {
         "_id": { "$gt": null }
       },
       {
         "year": {
           "$in": [2014, 2015]
         }
       }
     ],
     "com.cloudant.meta.auth.users": { "$in": [ "USER" ] }
 ]
 }
```

**Comment by glynnbird** [comment]
had a first go at this: https://github.com/glynnbird/envoy/tree/cquery. 

Indexing `com.cloudant.meta.auth.users` proved problematic. Switching to `com_cloudant_meta.auth.users` worked. Also switch "$in" for "$elemMatch".

**Comment by glynnbird** [comment]
I've tidied this up and added some tests: https://github.com/glynnbird/envoy/tree/cquery.

It broadly works ok with one proviso. Here's the rather long winded explanation:

Let's assume we have documents like this:

```{"i":1}```

So we define our index

```ccurl -X POST -d '{"fields":[i], "type":"json"}' /db/_index```

Envoy intercepts this request and instructs Cloudant to create and index like this:

```{"fields":[com_cloudant_meta.auth.users,i], "type":"json"}```

But when we query the index we do 

``` ccurl -X POST -d '{"selector":{ "i":1}}' /db/_find```

which gets translated by Envoy into:

``` {"selector":{"$and":[{"com_cloudant_meta.auth.users":{"$elemMatch":{"$eq":"MYUSER"}}},{"i":1}]}}```

Although the query works, Cloudant/Envoy returns a warning:

```
{ warning: 'no matching index found, create an index to optimize query time'...
```

Because it doesn't think it has an index that can help it. When the index type is "text" instead of "json" then everything's fine.

**Comment by willholley** [comment]
My initial reaction to this is that we shouldn't support `_index` at all through envoy. Developers / administrators of an application can add indexes directly in Cloudant - we just need to prevent information leaking when users query them.

Some gotchas that we'd need to catch if users can add their own indexes:
 1. default field support needs to be disabled
 1. array length support needs to be disabled
 1. an index defined by user A could break queries for user B (because index selection is naive)
